language: python
services:
- postgresql
python:
  - "2.7"
env:
  - DJANGO=1.7.5
addons:
  postgresql: "9.3"
# to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r requirements.txt --use-mirror
  - pip install coverage
before_script:
  - psql -c 'create database allegro_test;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
# command to run tests
script:
  - coverage run manage.py test --noinput allegro
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls