language: python
python:
  - "2.7"
env:
  - DJANGO=1.7.5
# to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r requirements.txt --use-mirror
  - pip install coverage
before_script:
  - manage.py syncdb --noinput
# command to run tests
script:
  - coverage run manage.py test --noinput allegro
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls